version: '3'
services: 
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules
      - .:/app
  # start up container for testing purpose (overriding the default CMD) (not so good since docker attach only attach to the primary process of the container)
  tests:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - ."/app"
    command: ["npm", "run", "test"]